{% set name = "py-cid" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py_cid-{{ version }}.tar.gz
  sha256: 93c62586c672353a9862f3fce13c9848ea39a00378e0980e2f0eed91631f3d28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - py-multibase >=1.0.0
    - py-multicodec >=1.0.0
    - morphys >=1.0
    - py-multihash >=3.0.0

test:
  imports:
    - cid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Self-describing content-addressed identifiers for distributed systems
  home: https://github.com/ipld/py-cid
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
